apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ee4aydxwz-go 
  janus-idp.io/tekton: ee4aydxwz-go
  backstage.io/kubernetes-id: ee4aydxwz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ee4aydxwz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml