apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ee4aydxwz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ee4aydxwz-go 
  name: ee4aydxwz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ee4aydxwz-go 
